version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: python main.py
          name: Run Trading Bot

workflows:
  trading-bot:
    jobs:
      - build-and-test